sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t m/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true m/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-447050614047"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


#Docker-env.eba-abnv2qvp.us-west-2.elasticbeanstalk.com